// Removed next/font/google import for Geist Mono
import "./globals.css";
import AuthProvider from "./AuthProvider";
import { NotesProvider } from "./contexts/NotesContext";
import { ModalProvider } from "./contexts/ModalContext";
import { SearchProvider } from "./contexts/SearchContext";
import { NotificationProvider } from "./contexts/NotificationContext";

import AppLayout from "./AppLayout";

// Remove font variable setup for Geist Mono

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        {/* Import Geist Mono from Vercel CDN */}
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@geist-ui/font@latest/geist-mono.css" />
      </head>
      <body
        className="font-geist-mono antialiased p-0 m-0 h-screen"
      >
        <AuthProvider>
          <NotificationProvider>
            <NotesProvider>
              <SearchProvider>
                <ModalProvider>
                  <AppLayout>{children}</AppLayout>
                </ModalProvider>
              </SearchProvider>
            </NotesProvider>
          </NotificationProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
